using System;
using NUnit.Framework;

namespace codewars.playing_with_digits
{
    public class playing_with_digits
    {
        [Test]
        [TestCase(89, 1, ExpectedResult = 1)]
        [TestCase(92, 1, ExpectedResult = -1)]
        [TestCase(695, 2, ExpectedResult = 2)]
        [TestCase(46288, 3, ExpectedResult = 51)]
        [TestCase(10383, 6, ExpectedResult = 12933)]
        public int DigPow_Test(int n, int k)
        {
            return DigPow(n, k);
        }

        /// <summary>
        /// Digs the pow.
        /// </summary>
        /// <param name="a">The a.</param>
        /// <param name="p">The p.</param>
        /// <returns>Is there an integer k such as : (a ^ p + b ^ (p+1) + c ^(p+2) + d ^ (p+3) + ...) = a * k</returns>
        /// <autogeneratedoc />
        private static int DigPow(int a, int p)
        {
            if (a < 1 || p < 1)
            {
                return -1;
            }

            double sum = 0;
            foreach (char c in a.ToString())
            {
                sum += Math.Pow(Char.GetNumericValue(c), p++);
            }

            for (int i = 1; i < sum / 2; i++)
            {
                if (a * i == sum)
                {
                    return i;
                }
            }

            return -1;
        }
    }
}