using NUnit.Framework;

/// <summary>
/// https://www.codewars.com/kata/highest-rank-number-in-an-array/train/csharp
/// </summary>
/// <autogeneratedoc />
namespace codewars
{
    public class Highest_Rank_Number__in_an_Array
    {
        [Test]
        [TestCase(new int[] { 12, 10, 8, 12, 7, 6, 4, 10, 12 }, ExpectedResult = 12, TestName = "eins")]
        [TestCase(new int[] { 12, 10, 8, 12, 7, 6, 4, 10, 12, 10 }, ExpectedResult = 12, TestName = "zwei")]
        [TestCase(new int[] { 12, 10, 8, 8, 3, 3, 3, 3, 2, 4, 10, 12, 10 }, ExpectedResult = 3, TestName = "drei")]
        [TestCase(new int[] { 12, 10 }, ExpectedResult = 12, TestName = "vier")]
        [TestCase(new int[] { 12, 10, 8, 12, 7, 6, 4, 10, 12 }, ExpectedResult = 12, TestName = "fuenf")]
        public int Highest_Rank_Number__in_an_Array_AreEqual(int[] arr)
        {
            int res = -1;
            int maxCount = 0;
            //foreach (int i in arr.Length)
            //{
            //    if (arr.arr.GetValue(i))
            //}

            return res;
        }
    }
}